(in-package :dexter)

(defgeneric key-press (responder event)
  (:documentation ""))
(defgeneric key-release (responder event)
  (:documentation ""))
(defgeneric button-press (responder event)
  (:documentation ""))
(defgeneric button-release (responder event)
  (:documentation ""))
(defgeneric motion-notify (responder event)
  (:documentation ""))
(defgeneric enter-notify (responder event)
  (:documentation ""))
(defgeneric leave-notify (responder event)
  (:documentation ""))
(defgeneric focus-in (responder event)
  (:documentation ""))
(defgeneric focus-out (responder event)
  (:documentation ""))
(defgeneric keymap-notify (responder event)
  (:documentation ""))
(defgeneric exposure (responder event)
  (:documentation ""))
(defgeneric graphics-exposure (responder event)
  (:documentation ""))
(defgeneric no-exposure (responder event)
  (:documentation ""))
(defgeneric visibility-notify (responder event)
  (:documentation ""))
(defgeneric create-notify (responder event)
  (:documentation ""))
(defgeneric destroy-notify (responder event)
  (:documentation ""))
(defgeneric unmap-notify (responder event)
  (:documentation ""))
(defgeneric map-notify (responder event)
  (:documentation ""))
(defgeneric map-request (responder event)
  (:documentation ""))
(defgeneric reparent-notify (responder event)
  (:documentation ""))
(defgeneric configure-notify (responder event)
  (:documentation ""))
(defgeneric configure-request (responder event)
  (:documentation ""))
(defgeneric property-notify (responder event)
  (:documentation ""))
(defgeneric selection-clear (responder event)
  (:documentation ""))
(defgeneric selection-request (responder event)
  (:documentation ""))
(defgeneric selection-notify (responder event)
  (:documentation ""))
(defgeneric colormap-notify (responder event)
  (:documentation ""))
(defgeneric client-message (responder event)
  (:documentation ""))
(defgeneric mapping-notify (responder event)
  (:documentation ""))

(defclass responder ()
  ((id :accessor id
       :initarg :id
       :initform ""
       :type string
       :documentation "A string ID for the responder.")))